var types = Ext.data.Types;
Ext.define('PForm.model.EcoDoppler', {
    extend: 'Ext.data.Model',
    fields: [
    	{name: 'id', type: types.NUMBER},
        {name: 'tableFechaIngreso', type: types.AUTO},
		{name: 'rutPac', type: types.AUTO},
		{name: 'infoEgesFur', type: types.AUTO},
		{name: 'infoEgesEg', type: types.AUTO},
		{name: 'infoEgesFpp', type: types.AUTO},
		{name: 'infoEgesEcoPrecoz', type: types.AUTO},
		{name: 'infoEgesFechaEcoPrecoz', type: types.AUTO},

		{name: 'infoAumbIP', type: types.AUTO},
		{name: 'infoAumbIR', type: types.AUTO},
		{name: 'infoAumbSD', type: types.AUTO},
		{name: 'infoAumbFlujoDiastolico', type: types.AUTO},
		{name: 'infoAumbPercentil', type: types.AUTO},
		{name: 'infoAumbConclusion', type: types.AUTO},
		{name: 'infoAcermedIP', type: types.AUTO},
		{name: 'infoAcermedIR', type: types.AUTO},
		{name: 'infoAcermedSD', type: types.AUTO},
		{name: 'infoAcermedFlujoDiastolico', type: types.AUTO},
		{name: 'infoAcermedPercentil', type: types.AUTO},
		{name: 'infoAcermedConclusion', type: types.AUTO},
		{name: 'infoAutederIP', type: types.AUTO},
		{name: 'infoAutederIR', type: types.AUTO},
		{name: 'infoAutederSD', type: types.AUTO},
		{name: 'infoAutederFlujoDiastolico', type: types.AUTO},
		{name: 'infoAutederPercentil', type: types.AUTO},
		{name: 'infoAutederConclusion', type: types.AUTO},
		{name: 'infoAuteizqIP', type: types.AUTO},
		{name: 'infoAuteizqIR', type: types.AUTO},
		{name: 'infoAuteizqSD', type: types.AUTO},
		{name: 'infoAuteizqFlujoDiastolico', type: types.AUTO},
		{name: 'infoAuteizqPercentil', type: types.AUTO},
		{name: 'infoAuteizqConclusion', type: types.AUTO},


		{name: 'biofDvenVelSistolicaMax', type: types.AUTO},
		{name: 'biofDvenVelDiasloticaMin', type: types.AUTO},
		{name: 'biofDvenIndiceSIP', type: types.AUTO},
		{name: 'biofDvenConclusion', type: types.AUTO},
		{name: 'biofAcermedVelSistolicaMax', type: types.AUTO},
		{name: 'biofAcermedVelDiasloticaMin', type: types.AUTO},
		{name: 'biofAcermedIndiceSIP', type: types.AUTO},
		{name: 'biofAcermedConclusion', type: types.AUTO},
		{name: 'biofVcovinfIPPosi', type: types.AUTO},
		{name: 'biofVcovinfIPPNega', type: types.AUTO},
		{name: 'biofVcovinfFlujoReverso', type: types.AUTO},
		{name: 'biofVcovinfConclusion', type: types.AUTO},
		{name: 'biofVumbIPPosi', type: types.AUTO},
		{name: 'biofVumbIPPNega', type: types.AUTO},
		{name: 'biofVumbFlujoReverso', type: types.AUTO},
		{name: 'biofVumbConclusion', type: types.AUTO},
		{name: 'biofFmitConslusion', type: types.AUTO},
		{name: 'biofFtriConslusion', type: types.AUTO},
		{name: 'biofPbioMovCorporales', type: types.AUTO},
		{name: 'biofPbioMovRespiratorios', type: types.AUTO},
		{name: 'biofPbioTonoFetal', type: types.AUTO},
		{name: 'biofPbioLiquidoOvular', type: types.AUTO},
		{name: 'biofPbioPlacenta', type: types.AUTO},
		{name: 'biofPbioLocalizacion', type: types.AUTO},




		{name: 'diagnObservaciones', type: types.AUTO},
		{name: 'diagnDiagnosticos', type: types.AUTO},
        {name: 'diagnEcografista', type: types.AUTO},
		{name: 'diagnBecado', type: types.AUTO},
		{name: 'diagnEquipo', type: types.AUTO},
		{name: 'diagnDerivada', type: types.AUTO},
		{name: 'diagnCitacion', type: types.AUTO},
		{name: 'diagnConclusiones', type: types.AUTO}
    ]
});