var types = Ext.data.Types;
Ext.define('PForm.model.SegundoTercerTrimestre', {
    extend: 'Ext.data.Model',
    fields: [
    	{name: 'id', type: types.NUMBER},
        {name: 'tableFechaIngreso', type: types.AUTO},
		{name: 'rutPac', type: types.AUTO},
		{name: 'infoEgesFur', type: types.AUTO},
		{name: 'infoEgesEg', type: types.AUTO},
		{name: 'infoEgesFpp', type: types.AUTO},
		{name: 'infoEgesEcoPrecoz', type: types.AUTO},
		{name: 'infoEgesFechaEcoPrecoz', type: types.AUTO},
        {name: 'infoEgesNumeroFetos', type: types.AUTO},
		{name: 'infoEgesGestacion', type: types.AUTO},
		{name: 'infoEgesGemelos', type: types.AUTO},
		{name: 'infoEgesGemelo', type: types.AUTO},
		
	
		{name: 'infoEgesCorioncicidad', type: types.AUTO},
		{name: 'infoEgesAmniocidad', type: types.AUTO},
		{name: 'infoEgesPosicion', type: types.AUTO},
		{name: 'infoEgesLcf', type: types.AUTO},
		{name: 'infoEgesFcardiaca', type: types.AUTO},
		{name: 'infoEgesPresentacion', type: types.AUTO},
		{name: 'infoEgesTroboflasto', type: types.AUTO},
		{name: 'infoEgesPlacenta', type: types.AUTO},
		{name: 'infoEgesLocalizacion', type: types.AUTO},
		{name: 'infoEgesInsercion', type: types.AUTO},
		{name: 'infoEgesMadurez', type: types.AUTO},
		{name: 'infoEgesInterfase', type: types.AUTO},
		{name: 'infoEgesCordon', type: types.AUTO},
		{name: 'infoEgesLa', type: types.AUTO},
		{name: 'infoEgesPresentaLa', type: types.AUTO},
		{name: 'infoEgesPresentaLaTabla', type: types.AUTO},	
		
		{name: 'biomGnrlDbp', type: types.AUTO},
		{name: 'biomGnrlDbpOpS', type: types.AUTO},
		{name: 'biomGnrlDbpOpD', type: types.AUTO},
		{name: 'biomGnrlFo', type: types.AUTO},
		{name: 'biomGnrlFoOpS', type: types.AUTO},
		{name: 'biomGnrlFoOpD', type: types.AUTO},
		{name: 'biomGnrlPx', type: types.AUTO},
		{name: 'biomGnrlPxOpS', type: types.AUTO},
		{name: 'biomGnrlPxOpD', type: types.AUTO},
		{name: 'biomGnrlAc', type: types.AUTO},
		{name: 'biomGnrlAcOpS', type: types.AUTO},
		{name: 'biomGnrlAcOpD', type: types.AUTO},
		{name: 'biomGnrlAbdomenAp', type: types.AUTO},
		{name: 'biomGnrlAbdomenApOpS', type: types.AUTO},
		{name: 'biomGnrlAbdomenApOpD', type: types.AUTO},
		{name: 'biomGnrlAbdomenTr', type: types.AUTO},
		{name: 'biomGnrlAbdomenTrOpS', type: types.AUTO},
		{name: 'biomGnrlAbdomenTrOpD', type: types.AUTO},
		{name: 'biomGnrlAbdomenPer', type: types.AUTO},
		{name: 'biomGnrlAbdomenPerOpS', type: types.AUTO},
		{name: 'biomGnrlAbdomenPerOpD', type: types.AUTO},
		{name: 'biomGnrlFemur', type: types.AUTO},
		{name: 'biomGnrlFemurOpS', type: types.AUTO},
		{name: 'biomGnrlFemurOpD', type: types.AUTO},
		{name: 'biomEstHuesLarHumero', type: types.AUTO},
		{name: 'biomEstHuesLarHumeroOpS', type: types.AUTO},
		{name: 'biomEstHuesLarHumeroOpD', type: types.AUTO},
		{name: 'biomEstHuesLarCubito', type: types.AUTO},
		{name: 'biomEstHuesLarCubitoOpS', type: types.AUTO},
		{name: 'biomEstHuesLarCubitoOpD', type: types.AUTO},
		{name: 'biomEstHuesLarRadio', type: types.AUTO},
		{name: 'biomEstHuesLarRadioOpS', type: types.AUTO},
		{name: 'biomEstHuesLarRadioOpD', type: types.AUTO},
		{name: 'biomEstHuesLarFemur', type: types.AUTO},
		{name: 'biomEstHuesLarFemurOpS', type: types.AUTO},
		{name: 'biomEstHuesLarFemurOpD', type: types.AUTO},
		{name: 'biomEstHuesLarTibia', type: types.AUTO},
		{name: 'biomEstHuesLarTibiaOpS', type: types.AUTO},
		{name: 'biomEstHuesLarTibiaOpD', type: types.AUTO},
		{name: 'biomEstHuesLarPerone', type: types.AUTO},
		{name: 'biomEstHuesLarPeroneOpS', type: types.AUTO},
		{name: 'biomEstHuesLarPeroneOpD', type: types.AUTO},

		{name: 'biomOtrasAnexAtrium', type: types.AUTO},
		{name: 'biomOtrasAnexAtriumIt', type: types.AUTO},
		{name: 'biomOtrasAnexCistMagna', type: types.AUTO},
		{name: 'biomOtrasAnexCistMagnaIt', type: types.AUTO},
		{name: 'biomOtrasAnexCerebelo', type: types.AUTO},
		{name: 'biomOtrasAnexCerebeloIt', type: types.AUTO},

		{name: 'biomEstPesoHadlock', type: types.AUTO},
		{name: 'biomEstPesoHadlockIt', type: types.AUTO},
		{name: 'biomEstPesoShepard', type: types.AUTO},
		{name: 'biomEstPesoShepardIt', type: types.AUTO},
		{name: 'biomEstPesoTodasHadlock', type: types.AUTO},
		{name: 'biomEstPesoodasHadlockIt', type: types.AUTO},

		{name: 'biomOtrasAnexFa', type: types.AUTO},
		{name: 'biomOtrasAnexFca', type: types.AUTO},
		{name: 'biomOtrasAnexDdbp', type: types.AUTO},
		{name: 'biomOtrasAnexCcca', type: types.AUTO},

		{name: 'biomPerfilBiofisicoMovCorporal', type: types.AUTO},
		{name: 'biomPerfilBiofisicoMovRespiratorio', type: types.AUTO},
		{name: 'biomPerfilBiofisicoTonoFetal', type: types.AUTO},
		{name: 'biomPerfilBiofisicoLiquidoOvular', type: types.AUTO},





		{name: 'diagnObservaciones', type: types.AUTO},
		{name: 'diagnDiagnosticos', type: types.AUTO},
        {name: 'diagnEcografista', type: types.AUTO},
		{name: 'diagnBecado', type: types.AUTO},
		{name: 'diagnEquipo', type: types.AUTO},
		{name: 'diagnDerivada', type: types.AUTO},
		{name: 'diagnCitacion', type: types.AUTO},
		{name: 'diagnConclusiones', type: types.AUTO}
    ]
});